export const SEAL_PIPELINE_PROGRAM = {
  id: "seal-pipeline-16wk",
  title: "Tactical Conditioning: 16-Week Pipeline Program",
  audience: "FOR PIPELINE CANDIDATES ONLY",
  audienceDetail: "This program is designed for candidates already in the SEAL/SWCC pipeline with a ship date — meaning you are already passing the PST at competitive scores, already running multiple miles regularly, already swimming distance, and already comfortable with high-volume calisthenics. This is NOT a beginner program. If you cannot currently complete the Week 1 baseline test in the listed scaling, you are not the audience for this plan — start with the NSW PTG or Stew Smith's Phase 1 instead.",
  author: "Max, former Navy SEAL, CSCS",
  disclaimer: "This is a Navy SEAL-inspired tactical conditioning program — NOT official Navy SEAL, Naval Special Warfare, or BUD/S training. Consult a medical professional before beginning. Never perform breath-hold training, underwater swimming, or water confidence drills alone. Stop training and seek help if experiencing chest pain, dizziness, faintness, sharp joint pain, severe shortness of breath, or unusual symptoms.",
  goal: "Build endurance, strength, muscular stamina, swimming capacity, running durability, and tactical work capacity over 16 weeks for candidates already at pipeline-level fitness.",
  phases: [
    { weeks: "1-4", name: "Base Phase" },
    { weeks: "5-8", name: "Volume Phase" },
    { weeks: "9-12", name: "Tactical Conditioning Phase" },
    { weeks: "13-15", name: "Peak Phase" },
    { weeks: "16", name: "Taper and Final Testing" },
  ],
  schedule: [
    { day: "Monday", focus: "Run + bodyweight conditioning" },
    { day: "Tuesday", focus: "Swim + strength training" },
    { day: "Wednesday", focus: "Run intervals + core" },
    { day: "Thursday", focus: "Swim + strength training" },
    { day: "Friday", focus: "Long run + grinder circuit" },
    { day: "Saturday", focus: "Swim, ruck, mobility, or active recovery" },
    { day: "Sunday", focus: "Full rest" },
  ],
  scaling: {
    beginner: "Complete 60-70% of listed volume. Use assisted pull-ups, incline push-ups, and shorter runs/swims.",
    intermediate: "Complete the plan as written.",
    advanced: "Complete 110-125% of bodyweight volume and upper end of run/swim distances. Do not increase volume and intensity simultaneously.",
  },
  benchmarks: {
    when: "Week 1, Week 8, Week 16",
    tests: [
      "500-yard swim",
      "Max push-ups in 2 minutes",
      "Max sit-ups in 2 minutes",
      "Max strict pull-ups",
      "1.5-mile run",
      "Optional: 4-mile run",
    ],
  },
  warmup: [
    "5 minutes easy jog, bike, row, or jump rope",
    "10 arm circles forward/back",
    "10 leg swings each direction",
    "10 walking lunges",
    "10 air squats",
    "10 scapular pull-ups or band pull-aparts",
    "30-second plank",
  ],
  cooldown: [
    "5 minutes easy walk",
    "Calf stretch: 45 seconds each side",
    "Hip flexor stretch: 45 seconds each side",
    "Hamstring stretch: 45 seconds each side",
    "Lat/shoulder stretch: 45 seconds each side",
    "Easy nasal breathing for 2 minutes",
  ],
  recoveryRules: [
    "One full rest day per week is mandatory.",
    "Reduce running volume 30-50% if shin, knee, ankle, hip, or foot pain develops.",
    "Avoid maxing out strength lifts during peak endurance weeks.",
    "Prioritize sleep, hydration, carbohydrates, and protein.",
    "Never perform breath-hold or underwater drills alone.",
    "Scale down if soreness lasts longer than 72 hours or performance drops sharply for multiple sessions.",
  ],
  performanceTargets: {
    beginner: [
      "500-yard swim completed safely",
      "40+ push-ups",
      "50+ sit-ups",
      "5+ pull-ups",
      "1.5-mile run without walking",
    ],
    intermediate: [
      "500-yard swim under 11:00",
      "70+ push-ups",
      "75+ sit-ups",
      "12+ pull-ups",
      "1.5-mile run under 10:30",
    ],
    advanced: [
      "500-yard swim under 9:30",
      "90+ push-ups",
      "90+ sit-ups",
      "18+ pull-ups",
      "1.5-mile run under 9:30",
      "4-mile run under 30:00",
    ],
  },
  weeks: [
    {
      number: 1,
      title: "Base Assessment",
      goal: "Establish baseline and learn movement standards.",
      runVolume: "8 miles",
      swimVolume: "2,000 yards",
      days: [
        { day: 1, title: "Baseline Test", duration: "60 min", blocks: [
          "500-yard swim for time",
          "Rest 10 minutes",
          "Max push-ups in 2 minutes",
          "Rest 2 minutes",
          "Max sit-ups in 2 minutes",
          "Rest 2 minutes",
          "Max strict pull-ups",
          "Rest 10-15 minutes",
          "1.5-mile run for time",
        ]},
        { day: 2, title: "Strength A + Easy Swim", duration: "60 min", blocks: [
          "Back squat: 3 x 5",
          "Bench press: 3 x 5",
          "Barbell row: 3 x 8",
          "Farmer carry: 4 x 40 yards",
          "Easy swim: 600 yards",
        ]},
        { day: 3, title: "Easy Run + Calisthenics", duration: "45 min", blocks: [
          "Easy run: 2 miles",
          "Push-ups: 5 x 15",
          "Pull-ups: 5 x max controlled reps",
          "Sit-ups: 4 x 20",
          "Flutter kicks: 4 x 20",
        ]},
        { day: 4, title: "Swim Technique + Core", duration: "45 min", blocks: [
          "Swim: 800 yards easy",
          "Tread water: 5 minutes",
          "Plank: 3 x 45 seconds",
          "Side plank: 2 x 30 seconds each side",
        ]},
        { day: 5, title: "Long Run + Grinder", duration: "60 min", blocks: [
          "Long run: 3 miles easy",
          "5 rounds: 15 push-ups, 5 pull-ups (assisted ok), 20 air squats, 20 sit-ups",
        ]},
        { day: 6, title: "Mobility or Easy Walk", duration: "30 min", blocks: [
          "20-30 minute walk",
          "Full-body mobility",
        ]},
        { day: 7, title: "Rest", duration: "—", blocks: ["Full rest day"] },
      ],
    },
    {
      number: 2, title: "Build Consistency", goal: "Build consistency.",
      runVolume: "10 miles", swimVolume: "2,400 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 3 miles", "Push-ups: 6 x 15", "Pull-ups: 6 x max", "Sit-ups: 5 x 20", "Flutter kicks: 5 x 20"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 1,000 yards", "Deadlift: 3 x 5", "Overhead press: 3 x 5", "Walking lunges: 3 x 10 each leg", "Hanging knee raises: 3 x 10"]},
        { day: 3, title: "Intervals + Core", blocks: ["6 x 400m at hard but controlled pace", "Rest 90 sec between repeats", "Plank: 3 x 1 minute", "Mountain climbers: 3 x 40"]},
        { day: 4, title: "Swim Technique", blocks: ["Swim: 800 yards technique", "Tread water: 8 minutes", "Easy mobility"]},
        { day: 5, title: "Long Run + Grinder", blocks: ["Long run: 4 miles", "5 rounds: 20 push-ups, 5 pull-ups, 25 sit-ups, 25 flutter kicks"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 600 yards or 30-minute walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 3, title: "Add Run Volume", goal: "Add a fourth run day.",
      runVolume: "12 miles", swimVolume: "2,800 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 3 miles", "Push-ups: 100 total", "Pull-ups: 30 total", "Sit-ups: 100 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 1,000 yards", "Back squat: 4 x 5", "Bench press: 4 x 5", "Row: 4 x 8", "Farmer carry: 5 x 40 yards"]},
        { day: 3, title: "Intervals + Conditioning", blocks: ["8 x 400m", "Burpees: 4 x 10", "Flutter kicks: 4 x 25"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,000 yards", "Tread water: 10 minutes"]},
        { day: 5, title: "Long Run + 8-Counts", blocks: ["Long run: 5 miles", "8-count bodybuilders: 5 x 10"]},
        { day: 6, title: "Recovery Run", blocks: ["Recovery run: 2 miles easy", "Mobility: 20 minutes"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 4, title: "Consolidate Base", goal: "Consolidate base fitness.",
      runVolume: "14 miles", swimVolume: "3,200 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 3 miles", "Push-ups: 120 total", "Pull-ups: 35 total", "Sit-ups: 120 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 1,200 yards", "Deadlift: 3 x 5", "Overhead press: 3 x 5", "Romanian deadlift: 3 x 8", "Dips: 3 x max"]},
        { day: 3, title: "Tempo + Core", blocks: ["Tempo run: 2 miles at comfortably hard pace", "4 rounds: 25 sit-ups, 25 flutter kicks, 30-second plank"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,200 yards", "Tread water: 12 minutes"]},
        { day: 5, title: "Long Run + Grinder", blocks: ["Long run: 6 miles", "6 rounds: 20 push-ups, 5 pull-ups, 20 lunges, 25 sit-ups"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 800 yards or mobility"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 5, title: "Begin Volume Build", goal: "Begin volume build.",
      runVolume: "16 miles", swimVolume: "4,000 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 4 miles", "Push-ups: 150 total", "Pull-ups: 40 total", "Sit-ups: 150 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 1,500 yards", "Back squat: 4 x 5", "Bench press: 4 x 5", "Row: 4 x 8", "Farmer carry: 5 x 50 yards"]},
        { day: 3, title: "Long Intervals", blocks: ["5 x 800m", "Rest 2 minutes", "Flutter kicks: 5 x 30"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,200 yards", "Tread water: 15 minutes", "Mobility"]},
        { day: 5, title: "Long Run + Grinder", blocks: ["Long run: 6 miles", "7 rounds: 20 push-ups, 6 pull-ups, 25 sit-ups, 10 burpees"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 1,300 yards or 45-minute ruck/walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 6, title: "Improve Stamina", goal: "Improve muscular stamina.",
      runVolume: "18 miles", swimVolume: "4,500 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 4 miles", "Push-ups: 175 total", "Pull-ups: 45 total", "Sit-ups: 175 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 1,600 yards", "Deadlift: 4 x 4", "Overhead press: 4 x 5", "Walking lunges: 4 x 12 each leg", "Hanging knee raises: 4 x 10"]},
        { day: 3, title: "Intervals", blocks: ["10 x 400m", "Rest 90 sec", "Burpees: 5 x 12"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,400 yards", "Tread water: 15 minutes"]},
        { day: 5, title: "Long Run + 8-Counts", blocks: ["Long run: 7 miles", "8-count bodybuilders: 75 total"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 1,500 yards"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 7, title: "Build Endurance", goal: "Build longer endurance.",
      runVolume: "20 miles", swimVolume: "5,000 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 5 miles", "Push-ups: 200 total", "Pull-ups: 50 total", "Sit-ups: 200 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 1,700 yards", "Back squat: 5 x 5", "Bench press: 4 x 5", "Row: 4 x 10", "Farmer carry: 6 x 50 yards"]},
        { day: 3, title: "Tempo + Core", blocks: ["Tempo run: 3 miles", "Flutter kicks: 150 total", "Plank: 4 x 1 minute"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,500 yards", "Tread water: 18 minutes"]},
        { day: 5, title: "Long Run + Grinder", blocks: ["Long run: 8 miles", "8 rounds: 20 push-ups, 6 pull-ups, 30 sit-ups, 20 air squats"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 1,800 yards or 60-minute ruck/walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 8, title: "Midpoint Deload + Test", goal: "Recover, then retest.",
      runVolume: "14 miles", swimVolume: "3,500 yards",
      days: [
        { day: 1, title: "Easy Run", blocks: ["Easy run: 3 miles", "Push-ups: 5 x 15", "Pull-ups: 5 x easy", "Sit-ups: 5 x 20"]},
        { day: 2, title: "Easy Swim + Light Strength", blocks: ["Easy swim: 1,000 yards", "Squat: 2 x 5", "Bench: 2 x 5", "Row: 2 x 8"]},
        { day: 3, title: "Benchmark Test", blocks: ["500-yard swim", "Max push-ups in 2 minutes", "Max sit-ups in 2 minutes", "Max pull-ups", "1.5-mile run"]},
        { day: 4, title: "Recovery", blocks: ["Mobility or easy walk"]},
        { day: 5, title: "Long Run", blocks: ["Long run: 5 miles easy", "Core: 10 minutes easy"]},
        { day: 6, title: "Easy Swim", blocks: ["Easy swim: 1,500 yards"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 9, title: "Tactical Conditioning Phase", goal: "Enter tactical conditioning phase.",
      runVolume: "22 miles", swimVolume: "5,500 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 5 miles", "Push-ups: 250 total", "Pull-ups: 60 total", "Sit-ups: 250 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 2,000 yards", "Back squat: 3 x 5", "Bench press: 3 x 5", "Row: 4 x 8", "Farmer carry: 6 x 60 yards"]},
        { day: 3, title: "Long Intervals + Burpees", blocks: ["6 x 800m", "Rest 2 minutes", "Burpees: 75 total"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,800 yards", "Tread water: 20 minutes"]},
        { day: 5, title: "Long Run + Big Grinder", blocks: ["Long run: 8 miles", "10 rounds: 20 push-ups, 5 pull-ups, 25 sit-ups, 25 flutter kicks"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 1,700 yards or 60-minute ruck/walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 10, title: "Hard-Work Tolerance", goal: "Increase hard-work tolerance.",
      runVolume: "24 miles", swimVolume: "6,000 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 5 miles", "Push-ups: 300 total", "Pull-ups: 70 total", "Sit-ups: 300 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 2,200 yards", "Deadlift: 3 x 5", "Overhead press: 3 x 5", "Romanian deadlift: 3 x 8", "Dips: 4 x max"]},
        { day: 3, title: "Intervals + Core", blocks: ["12 x 400m", "Rest 75-90 sec", "Flutter kicks: 250 total"]},
        { day: 4, title: "Swim + Optional Fins", blocks: ["Swim: 1,800 yards", "Optional fin swim: 800 yards easy"]},
        { day: 5, title: "Long Run + 8-Counts", blocks: ["Long run: 9 miles", "8-count bodybuilders: 100 total"]},
        { day: 6, title: "Easy Swim", blocks: ["Easy swim: 2,000 yards"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 11, title: "Peak Tactical Volume", goal: "Peak tactical volume.",
      runVolume: "26 miles", swimVolume: "6,500 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 6 miles", "Push-ups: 350 total", "Pull-ups: 80 total", "Sit-ups: 350 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 2,300 yards", "Front squat: 3 x 5", "Bench press: 3 x 5", "Row: 4 x 8", "Farmer carry: 6 x 60 yards"]},
        { day: 3, title: "Tempo + Core", blocks: ["Tempo run: 4 miles", "Flutter kicks: 300 total", "Plank: 5 x 1 minute"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 2,000 yards", "Tread water: 22 minutes"]},
        { day: 5, title: "Long Run + Big Grinder", blocks: ["Long run: 10 miles", "10 rounds: 25 push-ups, 6 pull-ups, 30 sit-ups, 10 burpees"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 2,200 yards or ruck/walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 12, title: "Deload", goal: "Absorb training and protect joints.",
      runVolume: "18 miles", swimVolume: "4,500 yards",
      days: [
        { day: 1, title: "Easy Run", blocks: ["Easy run: 4 miles", "Push-ups: 150 total", "Pull-ups: 40 total", "Sit-ups: 150 total"]},
        { day: 2, title: "Swim + Light Strength", blocks: ["Swim: 1,500 yards", "Squat: 2 x 5", "Press: 2 x 5", "Row: 2 x 8"]},
        { day: 3, title: "Smooth Intervals", blocks: ["6 x 400m smooth", "Core: 15 minutes"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 1,500 yards", "Tread water: 15 minutes"]},
        { day: 5, title: "Long Run Easy", blocks: ["Long run: 7 miles easy", "Light mobility"]},
        { day: 6, title: "Active Recovery", blocks: ["Easy swim: 1,500 yards or walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 13, title: "Begin Peak Phase", goal: "Begin peak phase.",
      runVolume: "28 miles", swimVolume: "7,000 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 6 miles", "Push-ups: 400 total", "Pull-ups: 100 total", "Sit-ups: 400 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 2,500 yards", "Squat: 3 x 3", "Bench press: 3 x 5", "Row: 4 x 8", "Farmer carry: 6 x 60 yards"]},
        { day: 3, title: "Fast Intervals + Burpees", blocks: ["10 x 400m fast", "Rest 75 seconds", "Burpees: 100 total"]},
        { day: 4, title: "Swim + Optional Fins", blocks: ["Swim: 2,000 yards", "Optional fin swim: 1,000 yards"]},
        { day: 5, title: "Long Run + Big Grinder", blocks: ["Long run: 10 miles", "12 rounds: 20 push-ups, 5 pull-ups, 25 sit-ups, 25 flutter kicks"]},
        { day: 6, title: "Long Swim", blocks: ["Long swim: 2,500 yards easy/moderate"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 14, title: "Endurance Confidence", goal: "Build final endurance confidence.",
      runVolume: "30 miles", swimVolume: "7,500 yards",
      days: [
        { day: 1, title: "Run + Calisthenics", blocks: ["Easy run: 6 miles", "Push-ups: 450 total", "Pull-ups: 110 total", "Sit-ups: 450 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 2,600 yards", "Deadlift: 3 x 3", "Overhead press: 3 x 5", "Walking lunges: 3 x 12 each leg", "Dips: 4 x max"]},
        { day: 3, title: "Tempo + Core", blocks: ["Tempo run: 5 miles", "Flutter kicks: 400 total"]},
        { day: 4, title: "Swim + Tread", blocks: ["Swim: 2,200 yards", "Tread water: 25 minutes"]},
        { day: 5, title: "Long Run + 8-Counts", blocks: ["Long run: 11 miles", "8-count bodybuilders: 150 total"]},
        { day: 6, title: "Long Swim or Ruck", blocks: ["Long swim: 2,700 yards or 75-minute ruck/walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 15, title: "Final Hard Week", goal: "Final hard week.",
      runVolume: "32 miles", swimVolume: "8,000 yards",
      days: [
        { day: 1, title: "Run + Big Calisthenics", blocks: ["Easy run: 7 miles", "Push-ups: 500 total", "Pull-ups: 125 total", "Sit-ups: 500 total"]},
        { day: 2, title: "Swim + Strength", blocks: ["Swim: 2,800 yards", "Squat: 3 x 3", "Bench press: 3 x 3", "Row: 4 x 8", "Farmer carry: 6 x 70 yards"]},
        { day: 3, title: "Hard Intervals + Burpees", blocks: ["6 x 800m hard", "Rest 2 minutes", "Burpees: 125 total"]},
        { day: 4, title: "Swim + Optional Fins", blocks: ["Swim: 2,400 yards", "Optional fin swim: 1,200 yards"]},
        { day: 5, title: "Long Run + Big Grinder", blocks: ["Long run: 12 miles", "12 rounds: 25 push-ups, 6 pull-ups, 30 sit-ups, 10 burpees"]},
        { day: 6, title: "Long Easy Swim", blocks: ["Long swim: 2,800 yards easy"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
    {
      number: 16, title: "Taper + Final Test", goal: "Recover and test performance.",
      runVolume: "12-16 miles", swimVolume: "3,500-4,500 yards",
      days: [
        { day: 1, title: "Easy Run + Light Calisthenics", blocks: ["Easy run: 3 miles", "Push-ups: 5 x 15", "Pull-ups: 5 x easy", "Sit-ups: 5 x 20", "Flutter kicks: 5 x 20"]},
        { day: 2, title: "Easy Swim + Mobility", blocks: ["Easy swim: 1,200 yards", "Mobility: 20 minutes"]},
        { day: 3, title: "Light Strength", blocks: ["Squat: 2 x 3 (light/moderate)", "Bench press: 2 x 3 (light/moderate)", "Row: 2 x 8", "Farmer carry: 3 x 40 yards"]},
        { day: 4, title: "Rest or Walk", blocks: ["Rest or 20-minute walk", "Mobility"]},
        { day: 5, title: "Final Benchmark Test", blocks: ["500-yard swim", "Max push-ups in 2 minutes", "Max sit-ups in 2 minutes", "Max strict pull-ups", "1.5-mile run", "Optional: 4-mile run on separate day"]},
        { day: 6, title: "Easy Swim", blocks: ["Easy swim: 1,500 yards or easy walk"]},
        { day: 7, title: "Rest", blocks: ["Full rest day"]},
      ],
    },
  ],
};
